name: Deploy Infrastructure and Build Application

on:
  workflow_dispatch:
    inputs:
      component:
        description: 'Component to deploy (backend1, backend2, or frontend)'
        required: true
        type: choice
        options:
        - backend1
        - backend2
        - frontend_web_app

jobs:
  deploy-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Build Application
      run: |
        cd ${{ github.event.inputs.component }}/application
        # npm install
        # npm run build

    - name: Zip build artifact
      run: |
        cd ${{ github.event.inputs.component }}/application/build
        zip -r build.zip .
    
    - name: Upload to Blob Storage
      run: |
        az storage blob upload....


    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: |
        cd ${{ github.event.inputs.component }}/infra
        terraform init -backend-config=backend-config/dev.config

    - name: Terraform Plan
      run: |
        cd ${{ github.event.inputs.component }}/infra
        terraform plan -var-file=vars/dev.tfvars

    - name: Terraform Apply
      run: |
        cd ${{ github.event.inputs.component }}/infra
        terraform apply -var-file=vars/dev.tfvars -auto-approve